---
- name: Get public IP from Telstra Smart Modem Gen3 and verify NANKUM PTY LTD
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    modem_base: "http://192.168.0.1"
    check_owner: "NANKUM PTY LTD"

  tasks:

    - name: Fetch modem homepage
      uri:
        url: "{{ modem_base }}/"
        method: GET
        return_content: yes
        user: "{{ username }}"
        password: "{{ password }}"
      register: modem_home

    - name: Extract public IP from homepage HTML
      set_fact:
        public_ip: "{{ modem_home.content | regex_search('((?:\\d{1,3}\\.){3}\\d{1,3})') }}"

    - name: Display public IP
      debug:
        msg: "Public IP: {{ public_ip }}"

    - name: Make HTTP request to public IP
      uri:
        url: "http://{{ public_ip }}"
        method: GET
        return_content: yes
      register: public_ip_page
      ignore_errors: yes

    - name: Display first 500 chars of the public IP page
      debug:
        msg: "{{ public_ip_page.content[:500] | default('No response from public IP') }}"

    - name: Print public IP in a parsable format for Jenkins
      debug:
        msg: "{{ public_ip }}"

